name: social_platform
description: "A new Flutter project.A simple social software"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  chewie: ^1.7.4
  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  shared_preferences: ^2.2.2
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4

flutter:
  uses-material-design: true
  assets:
    - assets/video/
    - assets/images/display/
    - assets/images/headImages/

  fonts:
    - family: socailPlatformIcon
      fonts:
        - asset: assets/font/iconfont.ttf
